version: 2.1

jobs:
  # Update Website
  website:
    docker:
    - image: circleci/golang:1.12.2
    steps:
    - run:
        working_directory: ~/workdir
        command: |
          git clone https://${GITHUB_TOKEN}@github.com/k8spatterns/k8spatterns.io.git
    - run:
        working_directory: ~/workdir
        environment:
          HUGO_VERSION: 0.54.0
          HUGO_URL: https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
        command: curl -sSL "$HUGO_URL" | tar -xz -C . hugo
    - run:
        working_directory: ~/workdir/k8spatterns.io
        command: ./gen_site.sh

workflows:
  version: 2
  k8spatterns.io:
    jobs:
    - website:
        filters:
          branches:
            only: master
