version: 2.1

orbs:
  hugo: circleci/hugo@0.1.0

jobs:
  # Update Website
  website:
    docker:
    - image: circleci/golang:1.12.2
    steps:
    - run:
        working_directory: ~/workdir
        command: |
          git clone --depth 1 https://${GITHUB_TOKEN}@github.com/k8spatterns/kubernetes-patterns.io.git
    - run:
        working_directory: ~/workdir/k8spatterns.io
        environment:
          HUGO_VERSION: 0.54.0
          HUGO_URL: https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        command: echo "$HUGO_URL" && curl -sSL "$HUGO_URL" | tar -xz -C . hugo
    - run:
        working_directory: ~/workdir/k8spatterns.io
        command: ./gen_site.sh

workflows:
  version: 2
  k8spatterns.io:
    jobs:
    - website:
        filters:
          branches:
            only: master
