apiVersion: "autoscaling.k8s.io/v1beta1"
kind: VerticalPodAutoscaler
metadata:
  name: random-generator
spec:
  updatePolicy:
    updateMode: Recreate
  selector:
    matchLabels:
      app: random-generator
