# Pod disruption budget
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: random-generator-pdb
spec:
  selector:
    matchLabels:
      # Used for counting active Pods for which this PDB is used
      app: random-generator
  # At least two need to be available all the time
  minAvailable: 4
