apiVersion: v1
kind: Service
metadata:
  name: random-generator
spec:
  selector:
    app: random-generator
  ports:
  - name: random
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prometheus
    port: 9889
    protocol: TCP
    targetPort: 9889
  type: NodePort
